// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANMrs6v8TnvC9b_maSkBT6YlL5T6Yl7Ro',
    appId: '1:333224777365:web:f37addaf735cb2b4046d9c',
    messagingSenderId: '333224777365',
    projectId: 'women-safety-2bbde',
    authDomain: 'women-safety-2bbde.firebaseapp.com',
    storageBucket: 'women-safety-2bbde.firebasestorage.app',
    measurementId: 'G-FXD46WPSY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKfw7smc1aPcXR4tU3hKLR1363b5OaAxc',
    appId: '1:333224777365:android:95d99a49e6a1b9be046d9c',
    messagingSenderId: '333224777365',
    projectId: 'women-safety-2bbde',
    storageBucket: 'women-safety-2bbde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzlHd-YmT01Q_jo5m8x18rKup0CFhvqr8',
    appId: '1:333224777365:ios:12fd477fc9b2267b046d9c',
    messagingSenderId: '333224777365',
    projectId: 'women-safety-2bbde',
    storageBucket: 'women-safety-2bbde.firebasestorage.app',
    iosBundleId: 'com.example.rescueastra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzlHd-YmT01Q_jo5m8x18rKup0CFhvqr8',
    appId: '1:333224777365:ios:12fd477fc9b2267b046d9c',
    messagingSenderId: '333224777365',
    projectId: 'women-safety-2bbde',
    storageBucket: 'women-safety-2bbde.firebasestorage.app',
    iosBundleId: 'com.example.rescueastra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX8p7oYedNL8BCU0Bf4P4Oq7woVvIKcBI',
    appId: '1:333224777365:web:289c8a3c31507eb5046d9c',
    messagingSenderId: '333224777365',
    projectId: 'women-safety-2bbde',
    authDomain: 'women-safety-2bbde.firebaseapp.com',
    storageBucket: 'women-safety-2bbde.firebasestorage.app',
    measurementId: 'G-WQS5Q9NCVG',
  );
}
